CcCREATE DATABASE "D597 Task 1";

--CREATE STAGE TABLES

CREATE TABLE "Fitness_trackers" (
     "Brand Name" varchar(20),
    "Device Type" varchar(20),
    "Model Name" varchar(100),
    "Color" varchar(100),
    "Selling Price" money ,
    "Original Price" money,
   "Display" varchar(50),
   "Rating (Out of 5)" decimal(3,1),
   "Strap Material" varchar(100),
	"Average Battery Life (in days)" int,
   "Reviews" int 
);

COPY "Fitness_trackers" FROM 'C:\Users\Public\D597 Task 1 Dataset 1_Fitness_trackers.csv' WITH (FORMAT CSV, HEADER true, DELIMITER ',');

SELECT *
	FROM public."Fitness_Trackers";


CREATE TABLE "medical_records" (
    "patient_id" int,
    "name" varchar(100),
    "date_of_birth" date,
    "gender" varchar(5),
    "medical_conditions" varchar(20),
    "medications" varchar(5),
    "allergies" varchar(50),
    "last_appointment_date" date,
    "tracker" varchar(100) 
);


COPY medical_records FROM 'C:\Users\Public\D597 Task 1 Dataset 3_medical_records.csv' WITH (FORMAT CSV, HEADER true, DELIMITER ',');

SELECT *
	FROM public."medical_records";

-- Create tracker_id
Alter Table public."Fitness_trackers"
ADD COLUMN tracker_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001 INCREMENT BY 1);

SELECT *
	FROM public."Fitness_Trackers";

--CREATE ADDITIONAL TABLES FROM STAGE TABLES

CREATE TABLE "tracker_product_info" (
    "tracker_id" int,
    "brand_name" varchar(20),
    "device_type" varchar(20),
    "model_name" varchar(100),
    "color" varchar(100),
    "display" varchar(50),
    "strap_material" varchar(100),
    "avg_battery_life_days" int,
    CONSTRAINT "pk_tracker_product_info" PRIMARY KEY (
        "tracker_id"
     )
);

CREATE TABLE "tracker_sales" (
    "tracker_id" int,
    "brand_name" varchar(20),
    "model_name" varchar(100),
    "selling_price" money,
    "original_price" money
);

CREATE TABLE "tracker_feedback" (
    "tracker_id" int,
    "brand_name" varchar(20),
    "model_name" varchar(100),
    "rating_out_of_5" decimal(3,1),
    "reviews" int
);


INSERT INTO tracker_product_info (tracker_id, brand_name, model_name, color, display,strap_material,avg_battery_life_days)
SELECT tracker_id, "Brand Name", "Model Name", "Color", "Display", "Strap Material", "Average Battery Life (in days)"
FROM public."Fitness_trackers";

INSERT INTO tracker_sales (tracker_id, brand_name, model_name, selling_price, original_price)
SELECT tracker_id, "Brand Name", "Model Name", "Selling Price", "Original Price"
FROM public."Fitness_trackers";

INSERT INTO tracker_feedback (tracker_id, brand_name, model_name, rating_out_of_5, reviews)
SELECT tracker_id, "Brand Name", "Model Name", "Rating (Out of 5)", "Reviews"
FROM public."Fitness_trackers";


-- Write script for three queries to retrieve specific information


-- Most used tracker models among patients (top 10)
select tracker, count(*) as patients_using
from medical_records
GROUP BY tracker
ORDER BY patients_using desc, tracker
LIMIT 10

Business value: Reveals which devices are the most popular amongst patients.

-- Top selling models used for Allergies
select f.brand_name
,f.model_name
,sum(f.selling_price) as total_sales
,count(m.allergies) as total_allergies
from public.tracker_sales f
JOIN public."medical_records" m ON f.model_name = m.tracker
GROUP BY f.brand_name,f.model_name
ORDER BY total_sales desc

Business value: Provides insights on whether allergies are the main driver for top selling trackers 

-- Total appointments by model and rating
select f.model_name
,f.rating_out_of_5
,count(m.last_appointment_date) as total_appointments
from public.tracker_feedback f
JOIN public."medical_records" m ON f.model_name = m.tracker
GROUP BY f.model_name, f.rating_out_of_5
ORDER BY total_appointments desc

Business value: Shows whether higher rated tracker devices prove more appointment engagement



-- Explain runtimes and Create Indexes for faster run times on queries

EXPLAIN ANALYZE
select tracker, count(*) as patients_using
from medical_records
GROUP BY tracker
ORDER BY patients_using desc, tracker
LIMIT 10

EXPLAIN ANALYZE
select f.brand_name
,f.model_name
,sum(f.selling_price) as total_sales
,count(m.allergies) as total_allergies
from public.tracker_sales f
JOIN public."medical_records" m ON f.model_name = m.tracker
GROUP BY f.brand_name,f.model_name
ORDER BY total_sales desc

EXPLAIN ANALYZE
select f.model_name
,f.rating_out_of_5
,count(m.last_appointment_date) as total_appointments
from public.tracker_feedback f
JOIN public."medical_records" m ON f.model_name = m.tracker
GROUP BY f.model_name, f.rating_out_of_5
ORDER BY total_appointments desc

CREATE INDEX idx_feedback_tracker_id ON public.tracker_feedback(tracker_id);
CREATE INDEX idx_sales_tracker_id ON public.tracker_sales(tracker_id);
CREATE INDEX idx_product_id ON public.tracker_product_info(tracker_id);
CREATE INDEX idx_medical_records ON public.medical_records(tracker);
CREATE INDEX idx_fitness_tracker ON public."Fitness_trackers"("Model Name");






